const Data = require('./database-mongo/index.js').Data

var data = [
  { "day": "Monday", 
    "occasion": "Leg Day #1 (Posterior Chain Dominant)",
    "workouts": [
      {"name": "Low-bar Squats",
        "amount": "5 sets, 5 reps",
      "description": "Pin the barbell tightly against the ‘shelf’ of your mid back, just below your shoulder muscles (posterior deltoids).\nEstablish a stable tripod foot.\nGenerate external rotation torque at the hips (Verbal cue: squeeze your glutes)\nCreate a rigid trunk by taking a big breath and holding it tight. (Verbal cue: big breath & core tight)\nHip hinge to engage the posterior-chain. (Verbal cue: hips back)\nRemain balanced by keeping the bar over the mid-foot during the entire squat.\nUse hip drive to stand up from the bottom position. (Verbal cue: drive the hips and chest up).",
      "videoLink": "https://www.youtube.com/embed/7fmrKmJMQnw"},
      {"name": "Romanian Deadlifts",
        "amount": "3 sets, 8-10 reps",
      "description": "Hold a bar at hip level with a pronated (palms facing down) grip. Your shoulders should be back, your back arched, and your knees slightly bent. This will be your starting position.\nLower the bar by moving your butt back as far as you can. Keep the bar close to your body, your head looking forward, and your shoulders back. Done correctly, you should reach the maximum range of your hamstring flexibility just below the knee. Any further movement will be compensation and should be avoided for this movement.\nAt the bottom of your range of motion, return the starting position by driving the hips forward to stand up tall.",
      "videoLink": "https://www.youtube.com/embed/2SHsk9AzdjA"},
      {"name": "Good Mornings",
        "amount": "4 sets, 8-10 reps",
      "description": "For the bodyweight version of the good morning stand with your feet shoulder-width apart and your hands placed behind your head. Stand upright, brace your core and pull your shoulders back. Take a breath and hinge forwards from your hips, not your waist, allowing a slight bend in your knees but keeping your back flat. Lean forwards until you feel a slight stretch in your hamstrings (but don’t go beyond horizontal), then, as you exhale, reverse the move to stand up straight.\nTo incorporate a resistance band into the move, stand on a large looped band with both feet and bring the other side of the loop over your head so it rests on your shoulders.\nWhen you progress to using a light barbell rest it across the back of your shoulders, not your neck. Hold the bar in place with both hands and perform the exercise as in the bodyweight version. Keep a tight grip on the bar, pulling it into the soft muscle of your shoulders as you lean forwards so it doesn’t put pressure on your neck.\nWhatever version of the good morning you are doing, make sure you avoid craning your neck to look forwards as you lean forwards. Instead, keep a neutral spine by looking forwards as you stand and towards the floor as you lower. Push your hips back to maintain balance and drive them forwards to initiate the force needed to return to standing.",
      "videoLink": "https://www.youtube.com/embed/5Xj6XUa77qc"},
      {"name": "Abductor Machine",
        "amount": "3 sets, 30 reps (10 leaned back, 10 sitting straight up, 10 leaning forward (no rest between each set of 10)",
      "description": "1.To begin, sit down on the abductor machine and select a weight you are comfortable with. When your legs are positioned properly, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position.\n2.Slowly press against the machine with your legs to move them away from each other while exhaling.\n3.Feel the contraction for a second and begin to move your legs back to the starting position while breathing in. Note: Remember to keep your upper body stationary to prevent any injuries from occurring.\n4.Repeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/GmRSV_n2E_0"},
      {"name": "Hip Thrusts",
        "amount": "5 sets, 10-12 reps",
      "description": "1. Focus on moving the weight with the glutes and not the lower back or hamstrings \n2. When you approach the top of the movement, finish the lift by contracting your glutes hard and pushing your hips forward. Do not overextend the lower back \n3. Finish the movement with your hips as high as possible while maintaining a neutral spine. At the top of the movement your torso should be parallel to the ground with hips pushed through\n4. Lower the weight under control keeping tension on the glutes \n 5. Repeat for desired number of reps",
      "videoLink": "https://www.youtube.com/embed/LM8XHLYJoYs"}
    ]
  },
  { "day": "Tuesday",
    "occasion": "Chest Day",
    "workouts": [
      {"name": "Barbell Incline Bench Press",
      "amount": "3-4 sets, 8-10 reps",
      "description": "Load the bar to an appropriate weight for your training.\nLay on the bench with your feet flat on the ground, driving through to your hips. Your back should be arched, and your shoulder blades retracted.\nTake a medium, pronated grip covering the rings on the bar. Remove the bar from the rack, holding the weight above your chest with your arms extended. This will be your starting position.\nLower the bar to the sternum by flexing the elbows. Maintain control and do not bounce the bar off of your chest. Your lats should stay tight and elbows slightly drawn in.\nAfter touching your torso with the bar, extend the elbows to return the bar to the starting position.",
      "videoLink": "https://www.youtube.com/embed/DbFgADa2PL8"},
      {"name": "Dumbbell Bench Press",
        "amount": "4 sets, 8-10 reps",
      "description": "Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.\nThen, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.\nOnce at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.\nThen, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it.\nRepeat the movement for the prescribed amount of repetitions of your training program.\nCaution: When you are done, do not drop the dumbbells next to you as this is dangerous to your rotator cuff in your shoulders and others working out around you.\nJust lift your legs from the floor bending at the knees, twist your wrists so that the palms of your hands are facing each other and place the dumbbells on top of your thighs. When both dumbbells are touching your thighs simultaneously push your upper torso up (while pressing the dumbbells on your thighs) and also perform a slight kick forward with your legs (keeping the dumbbells on top of the thighs). By doing this combined movement, momentum will help you get back to a sitting position with both dumbbells still on top of your thighs. At this moment you can place the dumbbells on the floor.",
      "videoLink": "https://www.youtube.com/embed/VmB1G1K7v94"},
      {"name": "Dumbbell Flyes",
        "amount": "4 sets, 8-10 reps",
      "description": "Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.\nThen using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you're pressing them, but stop and hold just before you lock out. This will be your starting position.\nWith a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.\nReturn your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.\nHold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.\nVariations: You may want to use a palms facing forward version for different stimulation.",
      "videoLink": "https://www.youtube.com/embed/eozdVDA78K0"},
      {"name": "Butterfly",
        "amount": "3 sets, 12-15 reps",
      "description": "Sit on the machine with your back flat on the pad.\nTake hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position.\nPush the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.\nReturn back to the starting position slowly as you inhale until your chest muscles are fully stretched.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/Qr7dstCeYtw"},
      {"name": "Bent-Arm Dumbbell Pullover",
        "amount": "3 sets, 12-15 reps",
      "description": "Place a dumbbell standing up on a flat bench.\nEnsuring that the dumbbell stays securely placed at the top of the bench, lie perpendicular to the bench (torso across it as in forming a cross) with only your shoulders lying on the surface. Hips should be below the bench and legs bent with feet firmly on the floor. The head will be off the bench as well.\nGrasp the dumbbell with both hands and hold it straight over your chest with a bend in your arms. Both palms should be pressing against the underside one of the sides of the dumbbell. This will be your starting position. Caution: Always ensure that the dumbbell used for this exercise is secure. Using a dumbbell with loose plates can result in the dumbbell falling apart and falling on your face.\nWhile keeping your arms locked in the bent arm position, lower the weight slowly in an arc behind your head while breathing in until you feel a stretch on the chest.\nAt that point, bring the dumbbell back to the starting position using the arc through which the weight was lowered and exhale as you perform this movement.\nHold the weight on the initial position for a second and repeat the motion for the prescribed number of repetitions.",
      "videoLink": "https://www.youtube.com/embed/tpLnfSQJ0gg"}
    ]
  },
  { "day": "Wednesday",
    "occasion": "Arms/Shoulders Day",
    "workouts": [
      {"name": "Preacher Curl",
        "amount": "5 sets, 3, 3, 2, 2, 1 reps",
      "description": "To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.\nAs you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.\nAs you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/fIWP-FRFNU0"},
      {"name": "Push Press",
        "amount": "5 sets, 3, 3, 2, 2, 1 reps",
      "description": "Beginning Position:\nUse the floor-to-shoulder lifting technique described in the Power Clean exercise to move the bar from the floor to the shoulders.\nUpward Movement Phase:\nSlightly flex the hips and knees, keeping torso erect.\nImmediately follow with an explosive push upward by extending the knees.\nKeep torso erect and tensed.\nAt maximum hip and knee extension, shift body weight to balls of feet and extend ankle joints.\nAt maximum plantar flexion, push bar from the shoulders.\nPush the bar with the arms to a fully extended elbow position overhead.\nDownward Movement Phase:\nLower bar to shoulders.\nFlex hips and knees slightly as bar touches shoulders.\nStraighten the hips and knees before the upward movement phase begins again.\nBreathing:\nExhale through the sticking point of the upward movement phase.\nInhale during the downward movement phase.",
      "videoLink": "https://www.youtube.com/embed/ep30avTSMB0"},
      {"name": "Front Dumbbell Raise",
        "amount": "3 sets, 12-15 reps",
      "description": "Pick a couple of dumbbells and stand with a straight torso and the dumbbells on front of your thighs at arms length with the palms of the hand facing your thighs. This will be your starting position.\nWhile maintaining the torso stationary (no swinging), lift the left dumbbell to the front with a slight bend on the elbow and the palms of the hands always facing down. Continue to go up until you arm is slightly above parallel to the floor. Exhale as you execute this portion of the movement and pause for a second at the top. Inhale after the second pause.\nNow lower the dumbbell back down slowly to the starting position as you simultaneously lift the right dumbbell.\nContinue alternating in this fashion until all of the recommended amount of repetitions have been performed for each arm.",
      "videoLink": "https://www.youtube.com/embed/-t7fuZ0KhDA"},
      {"name": "Dips - Triceps Version",
        "amount": "3 sets, 12-15 reps",
      "description": "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars.\nNow, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm.\nThen, exhale and push your torso back up using your triceps to bring your body back to the starting position.\nRepeat the movement for the prescribed amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/wjUmnZH528Y"},
      {"name": "Side Lateral Raise",
        "amount": "3 sets, 12-15 reps",
      "description": "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.\nWhile maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.\nLower the dumbbells back down slowly to the starting position as you inhale.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/3VcKaXpzqRo"}
    ]
  },
  { "day": "Thursday", 
    "occasion": "Back Day",
    "workouts": [
      {"name": "Pullups",
        "amount": "5 sets, max reps",
      "description": "Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.\nAs you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.\nPull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.\nAfter a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.\nRepeat this motion for the prescribed amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/eGo4IYlbE5g"},
      {"name": "Bent Over Barbell Row",
        "amount": "4 sets, 8-10 reps",
      "description": "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.\nNow, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.\nThen inhale and slowly lower the barbell back to the starting position.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/vT2GjY_Umpw"},
      {"name": "Straight-Arm Pulldown",
        "amount": "4 sets, 8-10 reps",
      "description": "You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so.\nBend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin.\nWhile keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step.\nWhile keeping the arms straight, go back to the starting position while breathing in.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/soX7zhZ7yfQ"},
      {"name": "Barbell Shrug",
        "amount": "3 sets, 12-15 reps",
      "description": "Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for a better grip. This will be your starting position.\nRaise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps.\nSlowly return to the starting position as you breathe in.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/NAqCVe2mwzM"},
      {"name": "V-Bar Pulldown",
        "amount": "3 sets, 12-15 reps",
      "description": "Sit down on a pull-down machine with a V-Bar attached to the top pulley.\nAdjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.\nGrab the V-bar with the palms facing each other (a neutral grip). Stick your chest out and lean yourself back slightly (around 30-degrees) in order to better engage the lats. This will be your starting position.\nUsing your lats, pull the bar down as you squeeze your shoulder blades. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion. Tip: Keep the torso stationary throughout the movement.\nAfter a second hold on the contracted position, slowly bring the bar back to the starting position as you breathe in.\nRepeat for the prescribed number of repetitions.",
      "videoLink": "https://www.youtube.com/embed/vZA2i35lmh0"}
    ]
  },
  { "day": "Friday",
    "occasion": "Leg Day #2 (Low weight/high reps)",
    "workouts": [
      {"name": "Front Squats",
        "amount": "5 sets, 8-10 reps",
      "description": "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control.\nLift the bar off the rack by first pushing with your legs and at the same time straightening your torso.\nStep away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).\nBegin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.\nBegin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.\nRepeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/wyDbagKS7Rg"},
      {"name": "Smith Machine Lunges",
        "amount": "3 sets, 8-10 reps",
      "description": "Set up in a smith machine with the bar on your traps in a split stance position.\nDescend by flexing both knees simultaneously and continue until the back knee touches the ground directly beneath the hip.\nDrive through the front foot and extend the knee as you return to the starting position.\nRepeat for the desired number of repetitions.",
      "videoLink": "https://www.youtube.com/embed/73CD40T-III"},
      {"name": "Hack Squat",
        "amount": "3 sets, 8-12 reps",
      "description": "1. Place the back of your torso against the back pad of the machine and hook your shoulders under the shoulder pads provided.\n2. Position your legs in the platform using a shoulder width medium stance with the toes slightly pointed out. Tip: Keep your head up at all times and also maintain the back on the pad at all times.\n3. Place your arms on the side handles of the machine and disengage the safety bars (which on most designs is done by moving the side handles from a facing front position to a diagonal position).\n4. Now straighten your legs without locking the knees. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).\n5. Begin to slowly lower the unit by bending the knees as you maintain a straight posture with the head up (back on the pad at all times). Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.\n6. Begin to raise the unit as you exhale by pushing the floor with mainly with the heel of your foot as you straighten the legs again and go back to the starting position.\n7. Repeat for the recommended amount of repetitions.",
      "videoLink": "https://www.youtube.com/embed/0tn5K9NlCfo"},
      {"name": "Leg Press",
        "amount": "4 sets, 10-12 reps",
      "description": "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).\nLower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.\nAs you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.\nPushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.\nRepeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.",
      "videoLink": "https://www.youtube.com/embed/IZxyjW7MPJQ"},
      {"name": "Leg Extension",
        "amount": "5 sets, 12-15 reps",
      "description": "For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position. Tip: You will need to adjust the pad so that it falls on top of your lower leg (just above your feet). Also, make sure that your legs form a 90-degree angle between the lower and upper leg. If the angle is less than 90-degrees then that means the knee is over the toes which in turn creates undue stress at the knee joint. If the machine is designed that way, either look for another machine or just make sure that when you start executing the exercise you stop going down once you hit the 90-degree angle.\nUsing your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position.\nSlowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit.\nRepeat for the recommended amount of times.",
      "videoLink": "https://www.youtube.com/embed/YyvSfVjQeL0"}
    ]
  },
];

Data.insertMany(data, (err) => {
  if (err) {
    console.log(err);
  } else {
    console.log('success!');
  }
});